services:
  - type: web
    name: travel-planner-backend
    env: docker
    plan: free
    region: oregon
    branch: master
    repo: https://github.com/Blianokoji/Travel_planner_backend
    autoDeploy: true
