services:
  - type: web
    name: travel-planner-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host=0.0.0.0 --port=8000"
    envVars:
      - key: FIREBASE_CREDENTIALS_PATH
        value: /etc/secrets/firebase_cred.json
      - key: JWT_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    secretFiles:
      - name: firebase_cred.json
        mountPath: /etc/secrets/firebase_cred.json
